namespace Korga.Filters.Entities;

public abstract class PersonFilter
{
    public long Id { get; set; }

    public long PersonFilterListId { get; set; }
    public PersonFilterList? PersonFilterList { get; set; }

    public string Discriminator { get; set; } = null!; // Generated by EF Core
    public string EqualityKey { get; set; } = null!; // Generated by the database
}
