// <auto-generated />
using System;
using Mailist;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mailist.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Mailist.EmailDelivery.Entities.OutboxEmail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("InboxEmailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InboxEmailId");

                    b.ToTable("OutboxEmails");
                });

            modelBuilder.Entity("Mailist.EmailDelivery.Entities.SentEmail", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ContentSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<long?>("InboxEmailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryTime");

                    b.HasIndex("InboxEmailId");

                    b.ToTable("SentEmails");
                });

            modelBuilder.Entity("Mailist.EmailRelay.Entities.DistributionList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Flags")
                        .HasColumnType("int");

                    b.Property<string>("RecipientsQuery")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasAlternateKey("Alias");

                    b.ToTable("DistributionLists");
                });

            modelBuilder.Entity("Mailist.EmailRelay.Entities.InboxEmail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Body")
                        .HasColumnType("longblob");

                    b.Property<long?>("DistributionListId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DownloadTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("From")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Header")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("ProcessingCompletedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Receiver")
                        .HasColumnType("longtext");

                    b.Property<string>("ReplyTo")
                        .HasColumnType("longtext");

                    b.Property<string>("Sender")
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("To")
                        .HasColumnType("longtext");

                    b.Property<uint?>("UniqueId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("DistributionListId");

                    b.HasIndex("ProcessingCompletedTime");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("InboxEmails");
                });

            modelBuilder.Entity("Mailist.EmailDelivery.Entities.OutboxEmail", b =>
                {
                    b.HasOne("Mailist.EmailRelay.Entities.InboxEmail", "InboxEmail")
                        .WithMany()
                        .HasForeignKey("InboxEmailId");

                    b.Navigation("InboxEmail");
                });

            modelBuilder.Entity("Mailist.EmailDelivery.Entities.SentEmail", b =>
                {
                    b.HasOne("Mailist.EmailRelay.Entities.InboxEmail", "InboxEmail")
                        .WithMany()
                        .HasForeignKey("InboxEmailId");

                    b.Navigation("InboxEmail");
                });

            modelBuilder.Entity("Mailist.EmailRelay.Entities.InboxEmail", b =>
                {
                    b.HasOne("Mailist.EmailRelay.Entities.DistributionList", "DistributionList")
                        .WithMany()
                        .HasForeignKey("DistributionListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DistributionList");
                });
#pragma warning restore 612, 618
        }
    }
}
