version: '2.1'

services:
  app:
    image: daniellerch/korga:latest
    restart: unless-stopped
    environment:
      # Change this according to your database settings
      - Database__ConnectionString=Server=db;Port=3306;Database=korga;User=korga;Password=korga;
      
      # Uncomment below if you want to use Korga in a subfolder like example.com/korga
      #- Hosting__PathBase=/korga

      # Uncomment below if you want to use Korga behind a reverse proxy like NGINX
      #- Hosting__AllowProxies=true
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=korga
      - MYSQL_USER=korga
      - MYSQL_PASSWORD=korga
    volumes:
      - ./data/mysql:/var/lib/mysql
