name: Ubuntu build and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and integration tests
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore NuGet packages
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Launch MySQL server
      run: sudo systemctl start mysql.service
    - name: Create database model
      run: dotnet run --configuration Release --no-build --project server/src/Korga.Server -- database create
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
