name: Ubuntu build and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and integration tests
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore NuGet packages
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Repare test environment
      run: |
        set -x

        # Launch and prepare MySQL server  
        sudo systemctl start mysql.service
        dotnet run -c Release --no-build -p server/src/Korga.Server -- database create --populate

        # Install and configure OpenLDAP server
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends slapd
        cat <<EOF | sudo debconf-set-selections
        slapd slapd/internal/generated_adminpw password admin
        slapd slapd/internal/adminpw password admin
        slapd slapd/password2 password admin
        slapd slapd/password1 password admin
        slapd slapd/dump_database_destdir string /var/backups/slapd-VERSION
        slapd slapd/domain string example.com
        slapd shared/organization string Example Church
        slapd slapd/purge_database boolean true
        slapd slapd/move_old_database boolean true
        slapd slapd/allow_ldap_v2 boolean false
        slapd slapd/no_configuration boolean false
        EOF
        sudo dpkg-reconfigure -f noninteractive slapd

        # Launch and prepare OpenLDAP server
        sudo systemctl start slapd.service
        dotnet run -c Release --no-build -p server/src/Korga.Server -- ldap create
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
